name: project-name

trigger:
  branches:
    include:
      - main
      - development
      - staging

resources:
  repositories:
    - repository: cicd-templates
      type: github
      name: kendedc/test-cicd-template
      ref: refs/heads/main
      endpoint: kendedc

variables:
- group: 'testing template app'

parameters:
- name: nodeVersion
  type: string
  default: "20.x"
- name: isTest
  type: boolean
  default: true

pool:
  name: Default
  demands:
    - Agent.Name -equals lazudautotest01

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Build
    displayName: "Build Job"
    steps:
    - template: build-node.yml@cicd-templates
      parameters:
        isTest: ${{ parameters.isTest }}
        nodeVersion: ${{ parameters.nodeVersion }}

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: Deploy
    displayName: "Deploy Job"
    steps:
    - template: deploy-static-web.yml@cicd-templates
