name: project-name

trigger:
  branches:
    include:
      - main
      - development
      - staging

resources:
  repositories:
    - repository: cicd-templates
      type: github
      name: kendedc/test-cicd-template
      ref: refs/heads/main
      endpoint: kendedc

parameters:
- name: azureSubscription
  type: string
  default: "sc-Ken-Test-Env-rg_de_core_dev_ea01"
- name: storageAccount
  type: string
  default: "cicdfrontendtest"
- name: nodeVersion
  type: string
  default: "20.x"

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: InstallNode
    displayName: "Install Node Job"
    steps:
    - template: install-node.yml@cicd-templates
      parameters:
        nodeVersion: ${{ parameters.nodeVersion }}
  - job: Build
    displayName: "Build Job"
    dependsOn: InstallNode
    steps:
    - template: ci-steps.yml@cicd-templates

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
    - job: Deploy
      displayName: "Deploy Job"
      steps:
        - checkout: none
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: "current"
            downloadType: "single"
            artifactName: "$(Build.BuildId)-drop"
            downloadPath: "$(System.ArtifactsDirectory)"

        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            scriptType: "bash"
            scriptLocation: "inlineScript"
            inlineScript: |
              az storage blob upload-batch -d "$web" --account-name "${{ parameters.storageAccount }}" --source "$(System.ArtifactsDirectory)/drop/dist" --overwrite
          displayName: "Deploy to Azure Storage"
