name: project-name

trigger:
  branches:
    include:
      - main
      - development
      - staging

resources:
  repositories:
    - repository: cicd-templates
      type: github
      name: kendedc/test-cicd-template
      ref: refs/heads/main
      endpoint: kendedc

variables:
- group: 'testing template app'

parameters:
- name: storageAccount
  type: string
  default: "cicdfrontendtest"
- name: nodeVersion
  type: string
  default: "20.x"

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: InstallNode
    displayName: "Install Node Job"
    steps:
    - template: install-node.yml@cicd-templates
      parameters:
        nodeVersion: ${{ parameters.nodeVersion }}
  - job: Build
    displayName: "Build Job"
    dependsOn: InstallNode
    steps:
    - template: ci-steps.yml@cicd-templates

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: Deploy
    displayName: "Deploy Job"
    steps:
    - checkout: none
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: "current"
        downloadType: "single"
        artifactName: "$(Build.BuildId)-drop"
        downloadPath: "$(System.ArtifactsDirectory)"

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(AZURE_SUBSCRIPTION)
        scriptType: "bash"
        scriptLocation: "inlineScript"
        inlineScript: |
          # If $web doesn't exist, enable static website and create $web container
          has_web=$( \
            az storage container exists \
              --name '$web' \
              --account-name '${{ parameters.storageAccount }}' \
              --account-key '$(STORAGE_KEY)' \
              --query "exists" \
              -o tsv || echo "false" \
          )
          if [ "$has_web" != "true" ]; then
            echo "'\$web' container not found. Enabling static website (creates \$web)..."
            az storage blob service-properties update \
              --account-name '${{ parameters.storageAccount }}' \
              --account-key '$(STORAGE_KEY)' \
              --static-website \
              --index-document index.html \
            echo "Static website enabled (created \$web)."
          else
            echo "'\$web' container exists."
          fi

          # upload to the special static-website container named $web
          az storage blob upload-batch \
            --destination '$web' \
            --account-name '${{ parameters.storageAccount }}' \
            --account-key '$(STORAGE_KEY)' \
            --source "$(System.ArtifactsDirectory)/$(Build.BuildId)-drop/dist" \
            --overwrite
      displayName: "Deploy to Azure Storage"
