name: project-name

trigger:
  branches:
    include:
      - main
      - development
      - staging

resources:
  repositories:
    - repository: cicd-templates
      type: github
      name: kendedc/test-cicd-template
      ref: refs/heads/main
      endpoint: kendedc

variables:
- group: 'testing template app'

parameters:
- name: nodeVersion
  type: string
  default: "20.x"
- name: isTest
  type: boolean
  default: true

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: InstallNode
    displayName: "Install Node Job"
    steps:
    - template: install-node.yml@cicd-templates
      parameters:
        nodeVersion: ${{ parameters.nodeVersion }}

  - job: Build
    displayName: "Build Job"
    dependsOn: InstallNode
    steps:
    - template: ci-steps.yml@cicd-templates
      parameters:
        isTest: ${{ parameters.isTest }}
        nodeVersion: ${{ parameters.nodeVersion }}
        preBuildSteps:
          - script: |
              echo "This is a pre-build custom step"
              echo "You can add any steps here that you want to run before the build"
              echo "NODE_ENV=production" > .env
              echo "Environment Variables in .env file:"
              cat .env
            displayName: "Custom Pre-Build Steps"
          - script: |
              yarn lint
            displayName: "Run Linter"

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - job: Deploy
    displayName: "Deploy Job"
    steps:
    - template: cd-steps.yml@cicd-templates
